### ISSUE TITLE
how to install SW in the platform. I have finished all the process in your readme

### ISSUE THREAD

**Issue by ShoneAlbert** [nvdla/vp#1]

**Comment by jarodw0723** [comment]
You can build the SW in https://github.com/nvdla/sw. Alternatively, there's a demo pre-built driver provided in https://github.com/nvdla/sw/tree/master/prebuilt/linux (drm.ko and opendla.ko). If you are using our demo lua files, here's how to intall the driver:

```sh
# Copy the driver files to the vp directory
# Execute the virtual simulator and login with 'root' and password 'nvdla'
mount -t 9p -o trans=virtio r /mnt
cd /mnt
insmod drm.ko
insmod opendla.ko
```

**Comment by jarodw0723** [comment]
After the driver is installed, please refer to http://nvdla.org/sw/test_application.html on test applications provided by our SW.

**Comment by ShoneAlbert** [comment]
I have done it, but it tells me some errors. vermagic is not right. I installed kernel 4.13.3. but it shows me need 4.13.16. 

![image](https://user-images.githubusercontent.com/22442214/33992917-5cc246de-e10f-11e7-809b-ca678bbf0cbc.png)

**Comment by jarodw0723** [comment]
Are you using the image file provided in our release? Can you try using the image file in https://github.com/nvdla/sw/tree/master/prebuilt/linux (Image and rootfs.ext4)?

**Comment by ShoneAlbert** [comment]
Is this successful?

![image](https://user-images.githubusercontent.com/22442214/33993398-572747d6-e111-11e7-825a-74f0b6ef0ad5.png)
because I have not the loadable file and input file

And thank you your answer very very much. I hope I can get more information of C model

**Comment by jarodw0723** [comment]
I just tried in my local, and the drm.ko and opendla.ko can be installed successfully. Do you build the image by yourself or use the ones that provided in the release?

**Comment by ShoneAlbert** [comment]
At first I build by my own, and I built it from the tutorial
![image](https://user-images.githubusercontent.com/22442214/33993825-1b009602-e113-11e7-94b3-47d81a8cbac6.png)
And failed 
After you told me use the prebuilt file , i try again ,the result is the second comment. So , a little frustrated

here is my script, edit some paths 
./build/bin/aarch64_toplevel --conf /home/liyihuang/vp/conf/aarch64_nvdla.lua

In lua file , I use the prebuilt file Image and rootfs.ext4

**Comment by jarodw0723** [comment]
Sorry about that. Let me be more clear, can you try the following:
1. rm -rf images/linux-4.13.3/*
2. cp  prebuilt/linux/* images/linux-4.13.3/
3. Execute the simulator, login, mount
4. cd /mnt/images/linux-4.13.3/
5. insmod drm.ko; insmod opendla.ko

The result should be:
```sh
# insmod drm.ko
# insmod opendla.ko
[   34.684558] opendla: loading out-of-tree module taints kernel.
[   34.700807] reset engine done
[   34.713180] [drm] Initialized nvdla 0.0.0 20171017 for 10200000.nvdla on minor 0
```

My guess about your failure is the 1st time the kernel is built on linux 4.13.16 which is the default of the latest buildroot, while our pre-built driver is build from linux 4.14.3. The 2nd time the error looks wired, I can only reproduced it if executing 'insmod drm.ko' multiple times. Please be noted that the init_dla.sh will execute insmod and install the driver, so no need to manually do it again if you use init_dla.sh.

**Comment by jwise** [comment]
The "cannot open shared library file" message -- try instead running `LD_LIBRARY_PATH=. ./nvdla_runtime`.  @prasshantg can you update the documentation for that (or rebuild those binaries with `-Wl,-rpath .`)?

**Comment by prasshantg** [comment]
Will update documentation

**Comment by JunningWu** [comment]
I have done all of the compile process with nvdla_compiler, which I got 1 output file output.protobuf and outdir alexnet/wisdom.dir, so which one is the loadable file?
with the prebuilt image and fs, I logged in the system and installed the drm.ko and opendla.ko, the log info is

# insmod drm.ko
# insmod opendla.ko 
[13640.620671] opendla: loading out-of-tree module taints kernel.
[13640.640333] reset engine done
[13640.656997] [drm] Initialized nvdla 0.0.0 20171017 for 10200000.nvdla on minor 0

when I run nvdla_runtime with output.protobuf, I faced up with the level 2 translation fault.

# ./nvdla_runtime --loadable output.protobuf 
creating new runtime context...
[13663.945446] nvdla_runtime[1306]: unhandled level 2 translation fault (11) at 0x2bf2565a, esr 0x92000006, in libnvdla_runtime.so[ffff96fe2000+21000]
[13663.952488] CPU: 0 PID: 1306 Comm: nvdla_runtime Tainted: G           O    4.13.3 #1
[13663.960354] Hardware name: linux,dummy-virt (DT)
[13663.969333] task: ffff80003db40e00 task.stack: ffff80003bf5c000
[13663.971616] PC is at 0xffff96ff7d98
[13663.977493] LR is at 0xffff96ff3984
[13663.980217] pc : [<0000ffff96ff7d98>] lr : [<0000ffff96ff3984>] pstate: 80000000
[13663.988488] sp : 0000fffff1551dd0
[13663.989760] x29: 0000fffff1551dd0 x28: 0000000000000000 
[13663.992999] x27: 0000000000000000 x26: 0000000000000000 
[13663.995787] x25: 0000000000000000 x24: 0000000000000000 
[13663.997707] x23: 0000000000000000 x22: 0000000000000000 
[13664.000649] x21: 0000000023cdc190 x20: 0000000000000000 
[13664.012200] x19: 000000002bf2565a x18: 0000000000000000 
[13664.012761] x17: 0000ffff97013fb0 x16: 0000ffff96ff7d98 
[13664.013022] x15: 0000000000000111 x14: 00000000000003f3 
[13664.013211] x13: 0000000000000000 x12: 0000ffff96fdf968 
[13664.013397] x11: 0000000000000022 x10: 0000000000000007 
[13664.013583] x9 : 0000000000001500 x8 : 0000000000000003 
[13664.013767] x7 : 0000000000000001 x6 : 0000000023cdc330 
[13664.016043] x5 : 0000000000000041 x4 : 0000000000000001 
[13664.016720] x3 : 0000ffff97014928 x2 : 0000ffff96ff3950 
[13664.016917] x1 : 0000000000000006 x0 : 000000002bf2565a 
Segmentation fault

Can you Help me out of this??


By the way, when I run the nvdla_compiler, I also got the same error, 

# ./nvdla_compiler -h
./nvdla_compiler: line 1: ELF: not found
./nvdla_compiler: line 2: syntax error: unexpected "("

**Comment by jarodw0723** [comment]
@wujunning2011 I think this is now duplicate with nvdla/sw#9, I'll leave the issue to our SW guys.

**Comment by blueardour** [comment]
@wujunning2011 
after run 'file' command on the prebuilt/linux folder. you can see the nvdla_compiler is a x86 formart executbe which is to be run on host machine.
While the nvdla_runtime is an 'ARM aarch64' executable which I think to be run in the simulator OS.

In my thought, after complie the CNN model in host machine by nvdla_compiler, one can run it in the simulator by the nvdla_runtime.
@jarodw0723  Correct me if any misunderstanding.

**Comment by JunningWu** [comment]
@blueardour Yes. You are right. 
We run the nvdla_compiler on the VM ubuntu14.04, and nvdla_runtime in the prebuilt linux Image which is used for Arm A57.

**Comment by prasshantg** [comment]
@ShoneAlbert @JunningWu @blueardour do you still see any issue? can this be closed?

**Comment by JunningWu** [comment]
@prasshantg No more issues, everything is ok.

**Comment by gitosu67** [comment]
Hi, @JunningWu @jwise how to generate the drm.ko module?
