### ISSUE TITLE
Link error when build virtual platform

### ISSUE THREAD

**Issue by jimchen2018** [nvdla/vp#12]
I got a link error as below:

[ 87%] Linking CXX executable aarch64_toplevel
**/usr/bin/ld: CMakeFiles/aarch64_toplevel.dir/src/aarch64_toplevel.cpp.o: undefined reference to symbol '_ZNKSs4findEPKcm@@GLIBCXX_3.4'**
//usr/lib/x86_64-linux-gnu/libstdc++.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/aarch64_toplevel.dir/build.make:106: recipe for target 'aarch64_toplevel' failed
make[2]: *** [aarch64_toplevel] Error 1
CMakeFiles/Makefile2:111: recipe for target 'CMakeFiles/aarch64_toplevel.dir/all' failed
make[1]: *** [CMakeFiles/aarch64_toplevel.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

Who can tell me what happens?  Where `findEPK` defines?
Thanks a lot!

**Comment by jimchen2018** [comment]
I solved this problem by adding **-lstdc++** in 
**vp/CMakeFiles/aarch64_toplevel.dir/link.txt**

**Comment by huayangshiboqi** [comment]
> I solved this problem by adding **-lstdc++** in
> **vp/CMakeFiles/aarch64_toplevel.dir/link.txt**

I solvedthis problem by adding one more argument: -c in
vp/CMakeFiles/aarch64_toplevel.dir/link.txt

**Comment by huayangshiboqi** [comment]
> I solved this problem by adding **-lstdc++** in
> **vp/CMakeFiles/aarch64_toplevel.dir/link.txt**

I solved this problem by reinstalling the SystemC
First, delet all SystemC in /usr/local directory
Then, according to the VP document, reinstall the SystemC
