### ISSUE TITLE
toplevel: -device virtio-9p-device,fsdev=r,mount_tag=r: 'virtio-9p-device' is not a valid device model name

### ISSUE THREAD

**Issue by xranger** [nvdla/vp#14]
according to the readme of vp, I have built a linux image (http://nvdla.org/vp.html#building-linux-kernel-for-nvdla-virtual-simulator). But when I continue to run the `./build/bin/aarch64_toplevel -c conf/aarch64_nvdla.lua`, it report : 
```
             SystemC 2.3.0-ASI --- Jun 20 2018 20:29:36
        Copyright (c) 1996-2012 by all Contributors,
        ALL RIGHTS RESERVED

No sc_log specified, will use the default setting
verbosity_level = SC_MEDIUM
bridge: tlm2c_elaborate..
toplevel: -device virtio-9p-device,fsdev=r,mount_tag=r: 'virtio-9p-device' is not a valid device model name
```
how to fix this?

thanks.

**Comment by HaiqingSun** [comment]
Hi
Please refer to https://github.com/nvdla/vp/issues/6 which has the same issue.

Best Regards,
Haiqing
