### ISSUE TITLE
Mounting on virtual platform

### ISSUE THREAD

**Issue by Adithyak1998** [nvdla/vp#15]
Hi,
I'm able to load the virtual platform from aarch64_toplevel, but when I try to mount using the command:
`mount -t 9p -o trans=virtio r /mnt`

I get an error:
`mount: mounting r on /mnt failed: No such device`

Please let me know how to solve this.

**Comment by Adithyak1998** [comment]
I fixed it.
I just had to change the arch64_nvdla.lua file to point to my kernel image and file system (output from buildroot)

**Comment by Jwy-jump** [comment]
@Adithyak1998 how to change the arch64_nvdla.lua file to point to my kernel image and file system?
