### ISSUE TITLE
make ERROR about auto_ptr!

### ISSUE THREAD

**Issue by liyang53719** [nvdla/vp#17]
$ make
[  5%] Built target tlm2c
[  6%] No force-build step for 'qbox'
[  6%] Performing build step for 'qbox'
[  6%] Performing install step for 'qbox'
[  8%] Completed 'qbox'
[ 13%] Built target qbox
[ 68%] Built target greenreg
[ 70%] Building CXX object fpga/aws-fpga/cosim_sc_wrapper.build/CMakeFiles/cosim_sc_wrapper.dir/src/nvdla_cosim_sc_wrapper.cpp.o
In file included from /usr/local/systemc-2.3.0/include/sysc/packages/boost/mem_fn.hpp:25:0,
                 from /usr/local/systemc-2.3.0/include/sysc/packages/boost/bind.hpp:26,
                 from /usr/local/systemc-2.3.0/include/sysc/kernel/sc_boost.h:44,
                 from /usr/local/systemc-2.3.0/include/sysc/kernel/sc_dynamic_processes.h:36,
                 from /usr/local/systemc-2.3.0/include/systemc:124,
                 from /usr/local/systemc-2.3.0/include/systemc.h:246,
                 from /home/liyang/Github/NVDLA/vp/fpga/aws-fpga/cosim_sc_wrapper/include/cosim_sc_wrapper/nvdla_cosim_sc_wrapper.h:14,
                 from /home/liyang/Github/NVDLA/vp/fpga/aws-fpga/cosim_sc_wrapper/src/nvdla_cosim_sc_wrapper.cpp:11:
/usr/local/systemc-2.3.0/include/sysc/packages/boost/get_pointer.hpp:21:40: error: ‘template<class> class std::auto_ptr’ is deprecated [-Werror=deprecated-declarations]
 template<class T> T * get_pointer(std::auto_ptr<T> const& p)
                                        ^
In file included from /usr/include/c++/5/memory:81:0,
                 from /usr/local/systemc-2.3.0/include/systemc.h:53,
                 from /home/liyang/Github/NVDLA/vp/fpga/aws-fpga/cosim_sc_wrapper/include/cosim_sc_wrapper/nvdla_cosim_sc_wrapper.h:14,
                 from /home/liyang/Github/NVDLA/vp/fpga/aws-fpga/cosim_sc_wrapper/src/nvdla_cosim_sc_wrapper.cpp:11:
/usr/include/c++/5/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^
cc1plus: all warnings being treated as errors
fpga/aws-fpga/cosim_sc_wrapper.build/CMakeFiles/cosim_sc_wrapper.dir/build.make:62: recipe for target 'fpga/aws-fpga/cosim_sc_wrapper.build/CMakeFiles/cosim_sc_wrapper.dir/src/nvdla_cosim_sc_wrapper.cpp.o' failed
make[2]: *** [fpga/aws-fpga/cosim_sc_wrapper.build/CMakeFiles/cosim_sc_wrapper.dir/src/nvdla_cosim_sc_wrapper.cpp.o] Error 1
CMakeFiles/Makefile2:3101: recipe for target 'fpga/aws-fpga/cosim_sc_wrapper.build/CMakeFiles/cosim_sc_wrapper.dir/all' failed
make[1]: *** [fpga/aws-fpga/cosim_sc_wrapper.build/CMakeFiles/cosim_sc_wrapper.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

I have installed systemc-2.3.0. I'm did something wrong?

**Comment by sun3388** [comment]
Looks like you are not using recommanded gcc version(4.8.4) in http://nvdla.org/vp.html ,  if you do need to use  this gcc version, just disable this warning as error.

**Comment by liyang53719** [comment]
Yes, I am using gcc-5. Your suggestion is very helpful. Thank you.

**Comment by keroles** [comment]
where Can i disable the warning
