### ISSUE TITLE
Segment fault

### ISSUE THREAD

**Issue by redglass1984** [nvdla/vp#20]
# ./nvdla_runtime --loadable ./VPtestfile/basic.nvdla --image ./VPtestfile/000456.jpg
creating new runtime context...
[   76.686715] random: crng init done
Emulator starting
surface format: 46
dlaimg height: 375 x 500 x 3: LS: 1504 SS: 0 Size: 564000
[ 3223.246633] nvdla_runtime[1273]: unhandled level 3 translation fault (11) at 0xffff7aec1000, esr 0x92000047, in libc-2.23.so[ffff91760000+12c000]
[ 3223.247392] CPU: 0 PID: 1273 Comm: nvdla_runtime Tainted: G           O    4.13.3 #1
[ 3223.247657] Hardware name: linux,dummy-virt (DT)
[ 3223.247878] task: ffff80003daf6200 task.stack: ffff80003ca70000
[ 3223.248266] PC is at 0xffff917d8494
[ 3223.248403] LR is at 0x409768
[ 3223.248521] pc : [<0000ffff917d8494>] lr : [<0000000000409768>] pstate: 20000000
[ 3223.250152] sp : 0000ffffe5a1cee0
[ 3223.250308] x29: 0000ffffe5a1cee0 x28: 0000000000000000 
[ 3223.250510] x27: 0000000000000000 x26: 0000000000000000 
[ 3223.250705] x25: 0000000000000000 x24: 0000000000000000 
[ 3223.250899] x23: 0000000000000000 x22: 0000000000000000 
[ 3223.251081] x21: 0000000000403408 x20: 0000000000000000 
[ 3223.251239] x19: 0000ffffe5a1df2d x18: 0000ffffe5a1ce6c 
[ 3223.251394] x17: 0000ffff917d8380 x16: 0000000000440348 
[ 3223.251551] x15: 00000000fffffffc x14: 0000000000000000 
[ 3223.251700] x13: 0000000000000000 x12: 0000000000000000 
[ 3223.251855] x11: 000031a632a72f88 x10: 0000000000000000 
[ 3223.252037] x9 : 0000000000000000 x8 : 0000000000000000 
[ 3223.252192] x7 : 0000310532062ec7 x6 : 0000ffff7aec0ff0 
[ 3223.252344] x5 : 0000000000000040 x4 : 0000000000000000 
[ 3223.252503] x3 : 0000ffff7ad2e000 x2 : 0000000000425d00 
[ 3223.254206] x1 : 0000ffff7a87e040 x0 : 0000ffff7ad2e000 
Segmentation fault
#

**Comment by redglass1984** [comment]
Using docker and prebuilt image. model is transferd from BVLC alexnet

**Comment by YJessicaGao** [comment]
I got same error. Any clue?

**Comment by davfre25** [comment]
Hi @redglass1984. How were you able to solve this?
