### ISSUE TITLE
??????????????help!!!!!!!!

### ISSUE THREAD

**Issue by Jwy-jump** [nvdla/vp#23]
/vp# ./build/bin/aarch64_toplevel -c conf/aarch64_nvdla.lua

             SystemC 2.3.0-ASI --- Jul 22 2018 23:30:28
        Copyright (c) 1996-2012 by all Contributors,
        ALL RIGHTS RESERVED

No sc_log specified, will use the default setting
verbosity_level = SC_MEDIUM
DMI mode enable
段错误 (核心已转储)
??????

**Comment by JSnobody** [comment]
Hi, I have the same problem! 
Have you solved it?
Please help me!
Thanks a lot!

**Comment by woshishui201020** [comment]
I have the same problem!
who can solve it?
Thanks！

**Comment by JSnobody** [comment]
Hi all, I solved it yesterday！
I found the error in libraryName("library", "no") of TLM2CSCBridge constructor.
I guessed the problem was related to OS as I used Ubuntu16.04 for working.
Then I used Ubuntu14.04 instead, and it worked.
I have passed the test! 
Thanks!

**Comment by Jwy-jump** [comment]
thanks! @JSnobody

**Comment by nicolast0604** [comment]
Can we modify the tlm2c to make it running on Ubuntu 18.04?
