### ISSUE TITLE
Is there any way that I can debug the hw cmodel in vp?

### ISSUE THREAD

**Issue by troyguo** [nvdla/vp#26]

**Comment by zhenpengzuo** [comment]
You can get the registers and memory access information by the method in the following website.
http://nvdla.org/vp.html
Debugging the Virtual Simulator

**Comment by troyguo** [comment]
thanks zhenpeng. Yes, I can debug the vp itself, what I really want is debugging the cmodel.  thanks anyway

**Comment by taog2018** [comment]
I do not what you mean "c model", c model is in VP.

**Comment by cmehrshad** [comment]
Perhaps this helps:
[Debugging virtual platform with gdb #11
](https://github.com/nvdla/vp/issues/11)

**Comment by troyguo** [comment]
> Perhaps this helps:
> [Debugging virtual platform with gdb #11](https://github.com/nvdla/vp/issues/11)
Thanks cmehrshad. That's what I wanted.
