### ISSUE TITLE
Inference time using NVDLA vp?

### ISSUE THREAD

**Issue by manojrohit** [nvdla/vp#33]
Is it possible to find out the inference time of the CNN model using vp at the momemt?

**Comment by DrVijayK** [comment]
For me it is taking hours. How about you?

**Comment by prasshantg** [comment]
@manojrohit we can't find inference time using VP. It uses CMOD and it is not cycle accurate model.

@DrVijayK it will take long time as even though it is DLA but still the CMOD is running on your host system CPU and doing all CNN calculations.

**Comment by DrVijayK** [comment]
@prasshantg Thanks for confirming.

**Comment by prasshantg** [comment]
@DrVijayK @manojrohit  you might want to check https://github.com/CSL-KU/firesim-nvdla It is faster than CMOD and cycle accurate.

**Comment by manojrohit** [comment]
Interesting work. Thanks for sharing @prasshantg

**Comment by prasshantg** [comment]
I am closing this issue, Please reopen if you still have any concerns or issues.

**Comment by jakc4103** [comment]
@DrVijayK May I ask how long it takes to inference 1 image?
Mine take 2 hours and still hanging...

**Comment by DrVijayK** [comment]
it used to take about 6-8 hrs.
