### ISSUE TITLE
vp can't make

### ISSUE THREAD

**Issue by long-a-zhang-tieto** [nvdla/vp#36]
zhanglong@onap-2:~/nvdla/vp$ cmake -DCMAKE_INSTALL_PREFIX=build -DSYSTEMC_PREFIX=/usr/local/systemc-2.3.3 -DNVDLA_HW_PREFIX=/home/zhanglong/nvdla/hw -DNVDLA_HW_PROJECT=nv_full
-- Searching for SystemC
-- SystemC version = 2.3.3
-- SystemC library = /usr/local/systemc-2.3.3/lib-linux64/libsystemc.so
-- Searching for TLM
running ls /usr/local/systemc-2.3.3/include/tlm.h 2>&1
/usr/local/systemc-2.3.3/include/tlm.h
-- TLM library = /usr/local/systemc-2.3.3/include/tlm.h
-- Searching for NVDLA CMOD
-- NVDLA HW VERSION = nvdla_os_initial
-- NVDLA CMOD include directory = /home/zhanglong/nvdla/hw/outdir/nv_full/cmod/release/include
-- NVDLA CMOD library directory = /home/zhanglong/nvdla/hw/outdir/nv_full/cmod/release/lib
-- NVDLA CMOD library = /home/zhanglong/nvdla/hw/outdir/nv_full/cmod/release/lib/libnvdla_cmod.so
-- Searching for SystemC
-- SystemC version = 2.3.3
-- SystemC library = /usr/local/systemc-2.3.3/lib-linux64/libsystemc.so
-- Searching for TLM
running ls /usr/local/systemc-2.3.3/include/tlm.h 2>&1
/usr/local/systemc-2.3.3/include/tlm.h
-- TLM library = /usr/local/systemc-2.3.3/include/tlm.h
-- Boost version: 1.65.1
-- Searching for SystemC
-- SystemC version = 2.3.3
-- SystemC library = /usr/local/systemc-2.3.3/lib-linux64/libsystemc.so
-- Searching for SystemC
-- SystemC version = 2.3.3
-- SystemC library = /usr/local/systemc-2.3.3/lib-linux64/libsystemc.so
-- Searching for TLM
running ls /usr/local/systemc-2.3.3/include/tlm.h 2>&1
/usr/local/systemc-2.3.3/include/tlm.h
-- TLM library = /usr/local/systemc-2.3.3/include/tlm.h
-- Searching for GreenLib
-- Boost version: 1.65.1
-- GreenLib include directory = /home/zhanglong/nvdla/vp/libs/greenlib/greencontrol/include
-- GreenLib library directory = /home/zhanglong/nvdla/vp/libs/greenlib/greenreg/lib
-- Searching for TLM2C
-- TLM2C include directory = /home/zhanglong/nvdla/vp/libs/tlm2c/include
-- TLM2C library directory = /home/zhanglong/nvdla/vp/libs/tlm2c.build
-- Searching for SystemC
-- SystemC version = 2.3.3
-- SystemC library = /usr/local/systemc-2.3.3/lib-linux64/libsystemc.so
-- Searching for TLM
running ls /usr/local/systemc-2.3.3/include/tlm.h 2>&1
/usr/local/systemc-2.3.3/include/tlm.h
-- TLM library = /usr/local/systemc-2.3.3/include/tlm.h
-- Searching for GreenLib
-- Boost version: 1.65.1
-- GreenLib include directory = /home/zhanglong/nvdla/vp/libs/greenlib/greencontrol/include
-- GreenLib library directory = /home/zhanglong/nvdla/vp/libs/greenlib/greenreg/lib
-- Searching for SystemC
-- SystemC version = 2.3.3
-- SystemC library = /usr/local/systemc-2.3.3/lib-linux64/libsystemc.so
-- Searching for TLM
running ls /usr/local/systemc-2.3.3/include/tlm.h 2>&1
/usr/local/systemc-2.3.3/include/tlm.h
-- TLM library = /usr/local/systemc-2.3.3/include/tlm.h
-- Searching for GreenLib
-- Boost version: 1.65.1
-- GreenLib include directory = /home/zhanglong/nvdla/vp/libs/greenlib/greencontrol/include
-- GreenLib library directory = /home/zhanglong/nvdla/vp/libs/greenlib/greenreg/lib
-- Searching for NVDLA CMOD
-- NVDLA HW VERSION = nvdla_os_initial
-- NVDLA CMOD include directory = /home/zhanglong/nvdla/hw/outdir/nv_full/cmod/release/include
-- NVDLA CMOD library directory = /home/zhanglong/nvdla/hw/outdir/nv_full/cmod/release/lib
-- NVDLA CMOD library = /home/zhanglong/nvdla/hw/outdir/nv_full/cmod/release/lib/libnvdla_cmod.so
-- Searching for SystemC
-- SystemC version = 2.3.3
-- SystemC library = /usr/local/systemc-2.3.3/lib-linux64/libsystemc.so
-- Searching for TLM
running ls /usr/local/systemc-2.3.3/include/tlm.h 2>&1
/usr/local/systemc-2.3.3/include/tlm.h
-- TLM library = /usr/local/systemc-2.3.3/include/tlm.h
-- Searching for GreenLib
-- Boost version: 1.65.1
-- GreenLib include directory = /home/zhanglong/nvdla/vp/libs/greenlib/greencontrol/include
-- GreenLib library directory = /home/zhanglong/nvdla/vp/libs/greenlib/greenreg/lib
-- Searching for SimpleCPU model.
-- SimpleCPU include directory = /home/zhanglong/nvdla/vp/models/cpu/include
-- SimpleCPU library directory = /home/zhanglong/nvdla/vp/models/cpu.build
-- Configuring done
-- Generating done
-- Build files have been written to: /home/zhanglong/nvdla/vp

zhanglong@onap-2:~/nvdla/vp$ make
Scanning dependencies of target greenreg
[  0%] Building CXX object libs/greenlib/greenreg/lib/CMakeFiles/greenreg.dir/__ /src/greenreg.cpp.o
In file included from /home/zhanglong/nvdla/vp/libs/greenlib/greensocket/include/greensocket/generic/green_socket_extension_support_base.h:144:0,
                 from /home/zhanglong/nvdla/vp/libs/greenlib/greensocket/include/greensocket/generic/green_socket_bind_checker.h:24,
                 from /home/zhanglong/nvdla/vp/libs/greenlib/greensocket/include/greensocket/initiator/green_initiator_socket_base.h:28,
                 from /home/zhanglong/nvdla/vp/libs/greenlib/greensocket/include/greensocket/initiator/single_socket.h:26,
                 from /home/zhanglong/nvdla/vp/libs/greenlib/gsgpsocket/include/gsgpsocket/transport/generic_transaction.h:29,
                 from /home/zhanglong/nvdla/vp/libs/greenlib/gsgpsocket/include/gsgpsocket/transport/GSGPSocket.h:32,
                 from /home/zhanglong/nvdla/vp/libs/greenlib/gsgpsocket/include/gsgpsocket/transport/GSGPSlaveSocket.h:24,
                 from /home/zhanglong/nvdla/vp/libs/greenlib/greenreg/include/greenreg/framework/core/gr_common.h:53,
                 from /home/zhanglong/nvdla/vp/libs/greenlib/greenreg/include/greenreg/greenreg.h:45,
                 from /home/zhanglong/nvdla/vp/libs/greenlib/greenreg/src/greenreg.cpp:35:
/home/zhanglong/nvdla/vp/libs/greenlib/greensocket/include/greensocket/generic/green_socket_extension_support_base.tpp: In static member function ‘static T* gs::socket::extension_support_base<TRAITS>::get_extension(const gs::ext::gs_data_id&, gs::socket::extension_support_base<TRAITS>::payload_type&)’:
/home/zhanglong/nvdla/vp/libs/greenlib/greensocket/include/greensocket/generic/green_socket_extension_support_base.tpp:127:29: error: expected primary-expression before ‘>’ token
   T* tmp=txn.get_extension<T>(); //get the pointer
                             ^
/home/zhanglong/nvdla/vp/libs/greenlib/greensocket/include/greensocket/generic/green_socket_extension_support_base.tpp:127:31: error: expected primary-expression before ‘)’ token
   T* tmp=txn.get_extension<T>(); //get the pointer
                               ^
In file included from /home/zhanglong/nvdla/vp/libs/greenlib/greencontrol/include/greencontrol/config.h:50:0,
                 from /home/zhanglong/nvdla/vp/libs/greenlib/gsgpsocket/include/gsgpsocket/transport/GSGPSocket.h:36,
                 from /home/zhanglong/nvdla/vp/libs/greenlib/gsgpsocket/include/gsgpsocket/transport/GSGPSlaveSocket.h:24,
                 from /home/zhanglong/nvdla/vp/libs/greenlib/greenreg/include/greenreg/framework/core/gr_common.h:53,
                 from /home/zhanglong/nvdla/vp/libs/greenlib/greenreg/include/greenreg/greenreg.h:45,
                 from /home/zhanglong/nvdla/vp/libs/greenlib/greenreg/src/greenreg.cpp:35:
/home/zhanglong/nvdla/vp/libs/greenlib/greencontrol/include/greencontrol/gcnf/apis/GCnf_Api/cnf_api_if.h: At global scope:
/home/zhanglong/nvdla/vp/libs/greenlib/greencontrol/include/greencontrol/gcnf/apis/GCnf_Api/cnf_api_if.h:237:65: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
   virtual sc_event& getUpdateEvent(const std::string &parname)  throw (RegisterObserverFailedException) = 0;
                                                                 ^~~~~
/home/zhanglong/nvdla/vp/libs/greenlib/greencontrol/include/greencontrol/gcnf/apis/GCnf_Api/cnf_api_if.h:325:40: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
   virtual sc_event& getNewParamEvent() throw (RegisterObserverFailedException) = 0;
                                        ^~~~~
In file included from /home/zhanglong/nvdla/vp/libs/greenlib/greencontrol/include/greencontrol/config.h:56:0,
                 from /home/zhanglong/nvdla/vp/libs/greenlib/gsgpsocket/include/gsgpsocket/transport/GSGPSocket.h:36,
                 from /home/zhanglong/nvdla/vp/libs/greenlib/gsgpsocket/include/gsgpsocket/transport/GSGPSlaveSocket.h:24,
                 from /home/zhanglong/nvdla/vp/libs/greenlib/greenreg/include/greenreg/framework/core/gr_common.h:53,
                 from /home/zhanglong/nvdla/vp/libs/greenlib/greenreg/include/greenreg/greenreg.h:45,
                 from /home/zhanglong/nvdla/vp/libs/greenlib/greenreg/src/greenreg.cpp:35:
/home/zhanglong/nvdla/vp/libs/greenlib/greencontrol/include/greencontrol/gcnf/apis/GCnf_Api/GCnf_Api_t.h:1013:57: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
   sc_event& getUpdateEvent(const std::string &parname)  throw (RegisterObserverFailedException) {
                                                         ^~~~~
/home/zhanglong/nvdla/vp/libs/greenlib/greencontrol/include/greencontrol/gcnf/apis/GCnf_Api/GCnf_Api_t.h:1134:32: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
   sc_event& getNewParamEvent() throw (RegisterObserverFailedException) {
                                ^~~~~
In file included from /home/zhanglong/nvdla/vp/libs/greenlib/greencontrol/include/greencontrol/config.h:57:0,
                 from /home/zhanglong/nvdla/vp/libs/greenlib/gsgpsocket/include/gsgpsocket/transport/GSGPSocket.h:36,
                 from /home/zhanglong/nvdla/vp/libs/greenlib/gsgpsocket/include/gsgpsocket/transport/GSGPSlaveSocket.h:24,
                 from /home/zhanglong/nvdla/vp/libs/greenlib/greenreg/include/greenreg/framework/core/gr_common.h:53,
                 from /home/zhanglong/nvdla/vp/libs/greenlib/greenreg/include/greenreg/greenreg.h:45,
                 from /home/zhanglong/nvdla/vp/libs/greenlib/greenreg/src/greenreg.cpp:35:
/home/zhanglong/nvdla/vp/libs/greenlib/greencontrol/include/greencontrol/gcnf/apis/GCnf_private_Api/gcnf_private_api_t.h:486:59: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
     sc_event& getUpdateEvent(const std::string &parname)  throw (RegisterObserverFailedException) {
                                                           ^~~~~
/home/zhanglong/nvdla/vp/libs/greenlib/greencontrol/include/greencontrol/gcnf/apis/GCnf_private_Api/gcnf_private_api_t.h:506:34: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
     sc_event& getNewParamEvent() throw (RegisterObserverFailedException) {
                                  ^~~~~
In file included from /home/zhanglong/nvdla/vp/libs/greenlib/greencontrol/include/greencontrol/gcnf/apis/gs_param/gs_param_class.h:33:0,
                 from /home/zhanglong/nvdla/vp/libs/greenlib/greencontrol/include/greencontrol/config.h:71,
                 from /home/zhanglong/nvdla/vp/libs/greenlib/gsgpsocket/include/gsgpsocket/transport/GSGPSocket.h:36,
                 from /home/zhanglong/nvdla/vp/libs/greenlib/gsgpsocket/include/gsgpsocket/transport/GSGPSlaveSocket.h:24,
                 from /home/zhanglong/nvdla/vp/libs/greenlib/greenreg/include/greenreg/framework/core/gr_common.h:53,
                 from /home/zhanglong/nvdla/vp/libs/greenlib/greenreg/include/greenreg/greenreg.h:45,
                 from /home/zhanglong/nvdla/vp/libs/greenlib/greenreg/src/greenreg.cpp:35:
/home/zhanglong/nvdla/vp/libs/greenlib/greencontrol/include/greencontrol/gcnf/apis/gs_param/gs_param_native.hpp: In member function ‘gs::cnf::gs_param<bool>::my_type& gs::cnf::gs_param<bool>::operator++()’:
/home/zhanglong/nvdla/vp/libs/greenlib/greencontrol/include/greencontrol/gcnf/apis/gs_param/gs_param_operator_macros.h:79:7: warning: use of an operand of type ‘bool’ in ‘operator++’ is deprecated [-Wdeprecated]
     ++tmp_val;                                                       \
       ^
/home/zhanglong/nvdla/vp/libs/greenlib/greencontrol/include/greencontrol/gcnf/apis/gs_param/gs_param_native.hpp:261:3: note: in expansion of macro ‘GC_SPECIALISATIONS_INCREMENT_OPERATORS’
   GC_SPECIALISATIONS_INCREMENT_OPERATORS;
   ^
/home/zhanglong/nvdla/vp/libs/greenlib/greencontrol/include/greencontrol/gcnf/apis/gs_param/gs_param_native.hpp: In member function ‘gs::cnf::gs_param<bool>::val_type gs::cnf::gs_param<bool>::operator++(int)’:
/home/zhanglong/nvdla/vp/libs/greenlib/greencontrol/include/greencontrol/gcnf/apis/gs_param/gs_param_operator_macros.h:89:16: warning: use of an operand of type ‘bool’ in ‘operator++’ is deprecated [-Wdeprecated]
     tmp_set_val++;                                                   \
                ^
/home/zhanglong/nvdla/vp/libs/greenlib/greencontrol/include/greencontrol/gcnf/apis/gs_param/gs_param_native.hpp:261:3: note: in expansion of macro ‘GC_SPECIALISATIONS_INCREMENT_OPERATORS’
   GC_SPECIALISATIONS_INCREMENT_OPERATORS;
   ^
libs/greenlib/greenreg/lib/CMakeFiles/greenreg.dir/build.make:62: recipe for target 'libs/greenlib/greenreg/lib/CMakeFiles/greenreg.dir/__/src/greenreg.cpp.o' failed
make[2]: *** [libs/greenlib/greenreg/lib/CMakeFiles/greenreg.dir/__/src/greenreg.cpp.o] Error 1
CMakeFiles/Makefile2:1810: recipe for target 'libs/greenlib/greenreg/lib/CMakeFiles/greenreg.dir/all' failed
make[1]: *** [libs/greenlib/greenreg/lib/CMakeFiles/greenreg.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by long-a-zhang-tieto** [comment]
the problem is from Greenlib, and i don't know how to solve it.
zhanglong@onap-2 : ~ /nvdla/vp/libs/greenlib$  cmake -DCMAKE_INSTALL_PREFIX=build -DSYSTEMC_PREFIX=/usr/local/systemc-2.3.3
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found SystemC: /usr/local/systemc-2.3.3/lib-linux64/libsystemc.so (found suitable version "2.3.3", minimum required is "2.3.0") 
-- Found TLM: /usr/local/systemc-2.3.3/include (found version "2.0.5") 
-- Boost version: 1.65.1
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so (found version "3.6.7") 
-- Found Lua: /usr/lib/x86_64-linux-gnu/liblua5.2.so;/usr/lib/x86_64-linux-gnu/libm.so (found version "") 
-- Found SWIG: /usr/bin/swig3.0 (found version "3.0.12") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/zhanglong/nvdla/vp/libs/greenlib
zhanglong@onap-2: ~ /nvdla/vp/libs/greenlib$ make check
Scanning dependencies of target check
Scanning dependencies of target greenscript
[  1%] Building CXX object greenscript/lib/CMakeFiles/greenscript.dir/__ /src/greenscript.cpp.o
/home/zhanglong/nvdla/vp/libs/greenlib/greenscript/src/greenscript.cpp: In constructor ‘gs::script::GreenScriptModule::GreenScriptModule(sc_core::sc_module_name, const char*)’:
/home/zhanglong/nvdla/vp/libs/greenlib/greenscript/src/greenscript.cpp:178:13: error: ‘PyString_FromString’ was not declared in this scope
   name_py = PyString_FromString(name());  // new ref
             ^~~~~~~~~~~~~~~~~~~
/home/zhanglong/nvdla/vp/libs/greenlib/greenscript/src/greenscript.cpp:178:13: note: suggested alternative: ‘PyLong_FromString’
   name_py = PyString_FromString(name());  // new ref
             ^~~~~~~~~~~~~~~~~~~
             PyLong_FromString
/home/zhanglong/nvdla/vp/libs/greenlib/greenscript/src/greenscript.cpp: In member function ‘void gs::script::GreenScriptModule::load(const char*)’:
/home/zhanglong/nvdla/vp/libs/greenlib/greenscript/src/greenscript.cpp:221:21: error: ‘PyString_AsString’ was not declared in this scope
       std::string s(PyString_AsString(path_py));
                     ^~~~~~~~~~~~~~~~~
/home/zhanglong/nvdla/vp/libs/greenlib/greenscript/src/greenscript.cpp:221:21: note: suggested alternative: ‘PyBytes_AsString’
       std::string s(PyString_AsString(path_py));
                     ^~~~~~~~~~~~~~~~~
                     PyBytes_AsString
/home/zhanglong/nvdla/vp/libs/greenlib/greenscript/src/greenscript.cpp: In member function ‘void gs::script::GreenScriptModule::add_to_pythonpath(const char*)’:
/home/zhanglong/nvdla/vp/libs/greenlib/greenscript/src/greenscript.cpp:262:23: error: ‘PyString_FromString’ was not declared in this scope
   PyObject *path_py = PyString_FromString(path);  // new ref
                       ^~~~~~~~~~~~~~~~~~~
/home/zhanglong/nvdla/vp/libs/greenlib/greenscript/src/greenscript.cpp:262:23: note: suggested alternative: ‘PyLong_FromString’
   PyObject *path_py = PyString_FromString(path);  // new ref
                       ^~~~~~~~~~~~~~~~~~~
                       PyLong_FromString
/home/zhanglong/nvdla/vp/libs/greenlib/greenscript/src/greenscript.cpp: In member function ‘bool gs::script::GreenScriptModule::private_load(const char*)’:
/home/zhanglong/nvdla/vp/libs/greenlib/greenscript/src/greenscript.cpp:278:28: error: ‘PyFile_FromString’ was not declared in this scope
   PyObject* PyFileObject = PyFile_FromString((char *)fullname, mode);
                            ^~~~~~~~~~~~~~~~~
/home/zhanglong/nvdla/vp/libs/greenlib/greenscript/src/greenscript.cpp:278:28: note: suggested alternative: ‘PyFile_WriteString’
   PyObject* PyFileObject = PyFile_FromString((char *)fullname, mode);
                            ^~~~~~~~~~~~~~~~~
                            PyFile_WriteString
In file included from /usr/include/python3.6m/Python.h:118:0,
                 from /home/zhanglong/nvdla/vp/libs/greenlib/greenscript/src/greenscript.cpp:38:
/home/zhanglong/nvdla/vp/libs/greenlib/greenscript/src/greenscript.cpp:279:30: error: ‘PyFile_AsFile’ was not declared in this scope
   PyObject *ret = PyRun_File(PyFile_AsFile(PyFileObject),
                              ^
/usr/include/python3.6m/pythonrun.h:162:23: note: in definition of macro ‘PyRun_File’
     PyRun_FileExFlags(fp, p, s, g, l, 0, NULL)
                       ^~
/home/zhanglong/nvdla/vp/libs/greenlib/greenscript/src/greenscript.cpp:279:30: note: suggested alternative: ‘PyFile_GetLine’
   PyObject *ret = PyRun_File(PyFile_AsFile(PyFileObject),
                              ^
/usr/include/python3.6m/pythonrun.h:162:23: note: in definition of macro ‘PyRun_File’
     PyRun_FileExFlags(fp, p, s, g, l, 0, NULL)
                       ^~
greenscript/lib/CMakeFiles/greenscript.dir/build.make:62: recipe for target 'greenscript/lib/CMakeFiles/greenscript.dir/__/src/greenscript.cpp.o' failed
make[7]: *** [greenscript/lib/CMakeFiles/greenscript.dir/__/src/greenscript.cpp.o] Error 1
CMakeFiles/Makefile2:1881: recipe for target 'greenscript/lib/CMakeFiles/greenscript.dir/all' failed
make[6]: *** [greenscript/lib/CMakeFiles/greenscript.dir/all] Error 2
CMakeFiles/Makefile2:108: recipe for target 'CMakeFiles/compile_test.dir/rule' failed
make[5]: *** [CMakeFiles/compile_test.dir/rule] Error 2
Makefile:197: recipe for target 'compile_test' failed
make[4]: *** [compile_test] Error 2
CMakeFiles/check.dir/build.make:57: recipe for target 'CMakeFiles/check' failed
make[3]: *** [CMakeFiles/check] Error 2
CMakeFiles/Makefile2:133: recipe for target 'CMakeFiles/check.dir/all' failed
make[2]: *** [CMakeFiles/check.dir/all] Error 2
CMakeFiles/Makefile2:140: recipe for target 'CMakeFiles/check.dir/rule' failed
make[1]: *** [CMakeFiles/check.dir/rule] Error 2
Makefile:210: recipe for target 'check' failed
make: *** [check] Error 2

**Comment by prasshantg** [comment]
@long-a-zhang-tieto please try with docker image (https://hub.docker.com/r/nvdla/vp) which has all dependencies install to build cmod and vp

Step 1. Run docker image
docker pull nvdla/vp
docker run -it -v /home:/home nvdla/vp

Step 2. Build CMOD
git clone https://github.com/nvdla/hw.git
cd hw/
git checkout origin/master
make

Creating tree.make to setup your working environment and projects
Enter project names      (Press ENTER if use: nv_small nv_small_256 nv_small_256_full nv_medium_512 nv_medium_1024_full nv_large):nv_small
Using designware or not [1 for use/0 for not use] (Press ENTER if use: 1):
Enter design ware path (Press ENTER if use: /home/tools/synopsys/syn_2011.09/dw/sim_ver):
Enter c pre-processor path (Press ENTER if use: /home/utils/gcc-4.8.2/bin/cpp):/usr/bin/cpp
Enter gcc path             (Press ENTER if use: /home/utils/gcc-4.8.2/bin/gcc):/usr/bin/gcc
Enter g++ path             (Press ENTER if use: /home/utils/gcc-4.8.2/bin/g++):/usr/bin/g++
Enter perl path            (Press ENTER if use: /home/utils/perl-5.10/5.10.0-threads-64/bin/perl):/usr/bin/perl
Enter java path            (Press ENTER if use: /home/utils/java/jdk1.8.0_131/bin/java):/usr/bin/java
Enter systemc path         (Press ENTER if use: /home/ip/shared/inf/SystemC/1.0/20151112/systemc-2.3.0/GCC472_64_DBG):/usr/local/systemc-2.3.0
Enter python path          (Press ENTER if use: /home/tools/continuum/Anaconda3-5.0.1/bin/python):/usr/bin/python
Enter vcs_home path        (Press ENTER if use: /home/tools/vcs/mx-2016.06-SP2-4):
Enter novas_home path      (Press ENTER if use: /home/tools/debussy/verdi3_2016.06-SP2-9):
Enter verdi_home path      (Press ENTER if use: /home/tools/debussy/verdi3_2016.06-SP2-9):
OPTIONAL: Enter verilator path (Press ENTER to use: verilator):
OPTIONAL: Enter clang path     (Press ENTER to use: /home/utils/llvm-4.0.1/bin/clang):

tools/bin/tmake -build cmod_top

Step 3. Build VP

cd ..

git clone https://github.com/nvdla/vp.git
cd vp/
git submodule update --init --recursive

cmake -DCMAKE_INSTALL_PREFIX=build -DSYSTEMC_PREFIX=/usr/local/systemc-2.3.0/ -DNVDLA_HW_PREFIX=<Path_to_hw_repo> -DNVDLA_HW_PROJECT=nv_small

**Comment by long-a-zhang-tieto** [comment]
thank you very much prasshantg. 
If I can run the vp from your setp1, what's the usage for step 2 and 3?

**Comment by prasshantg** [comment]
Step 2 and 3 are required either
- if you want to build cmod and vp yourself and want to try
- if you want to use nv_small or nv_large config since docker image contains cmod and vp only for nv_full config

**Comment by long-a-zhang-tieto** [comment]
well, very useful information, thank you very much
