### ISSUE TITLE
Segmentation fault when Running Kernel Image In the Virtual Simulato

### ISSUE THREAD

**Issue by jyang356** [nvdla/vp#39]
followed the instruction from http://nvdla.org/vp.html#prepare-kernel-image
after this command: ./build/bin/aarch64_toplevel -c conf/aarch64_nvdla.lua

             SystemC 2.3.0-ASI --- Jun 19 2019 10:14:15
        Copyright (c) 1996-2012 by all Contributors,
        ALL RIGHTS RESERVED

No sc_log specified, will use the default setting
verbosity_level = SC_MEDIUM
DMI mode enable
Segmentation fault (core dumped)

besides the location for Image nd rootfs.ext4, is there anything else i need to change in the aarch64_nvdla.lua file?
extra_arguments = "-machine virt -cpu cortex-a57 -machine type=virt -nographic -smp 1 -m 1024 -kernel /home/jingchi/vp/buildroot-2017.11-rc1/output/images/Image --append \"root=/dev/vda\" -drive file=/home/jingchi/vp/buildroot-2017.11-rc1/output/images/rootfs.ext4,if=none,format=raw,id=hd0 -device virtio-blk-device,drive=hd0 -fsdev local,id=r,path=.,security_model=none -device virtio-9p-device,fsdev=r,mount_tag=r -netdev user,id=user0,hostfwd=tcp::6666-:6666,hostfwd=tcp::6667-:22 -device virtio-net-device,netdev=user0"

**Comment by shazib-summar** [comment]
Hey @jyang356, any update on this? I'm facing the exact issue.

**Comment by jyang356** [comment]
no, i don't use this anymore
