### ISSUE TITLE
DLA_RUNTIME ERROR: unrecognized interface 0 

### ISSUE THREAD

**Issue by JunningWu** [nvdla/vp#4]
I trained and compiled the LeNet from Caffe github example, and Run the Test Inference using the test image from NVDLA_SW digits.
From the Inference log, I suppose the DLA running flow is OK, however there is an Error in the end.

# ./nvdla_runtime --softmax --loadable lenet.nvdla  --image two.pgm
creating new runtime context...
ppgminfo 1 28 28
pgm2dimg 1 28 28 1 32 896 896
submitting tasks...
[  727.191545] Enter:dla_read_network_config
[  727.193579] Exit:dla_read_network_config status=0
[  727.195396] Enter: dla_initiate_processors
[  727.198834] Enter: dla_submit_operation
[  727.206431] Prepare Convolution operation index 0 ROI 0 dep_count 1
[  727.212430] Enter: dla_prepare_operation

.......
.......
.......

[  785.230416] 11 HWLs done, totally 11 layers
[  785.230782] Enter: dla_free_op_desc op desc index 9 ROI 0
[  785.232123] Exit: dla_free_op_desc
[  785.232799] Enter: dla_free_op_desc op desc index 10 ROI 0
[  785.233598] Exit: dla_free_op_desc
[  785.233964] Exit:dla_op_completion processor SDP group1 status=0
[  785.234791] Exit:dla_handle_events, ret:0
[  785.235707] Enter:dla_handle_events, processor:PDP
[  785.236012] Exit:dla_handle_events, ret:0
[  785.236168] Enter:dla_handle_events, processor:CDP
[  785.236590] Exit:dla_handle_events, ret:0
[  785.237620] Enter:dla_handle_events, processor:RUBIK
[  785.238801] Exit:dla_handle_events, ret:0
[  785.241088] reset engine done
(DLA_RUNTIME) Error 0x00000004: unrecognized interface 0 (in Runtime.cpp, function submitInternal(), line 487)
(DLA_TEST) Error 0x00000004: runtime->submit() failed (in RuntimeTest.cpp, function runTest(), line 355)
(DLA_TEST) Error 0x00000004: (propagating from RuntimeTest.cpp, function run(), line 379)
(DLA_TEST) Error 0x00000004: (propagating from main.cpp, function launchTest(), line 92)

**Comment by jarodw0723** [comment]
@wujunning2011 It seems that this issue fits more for SW category, can you submit it to https://github.com/nvdla/sw/issues so that it can be better tracked and answered? Thanks!

**Comment by JunningWu** [comment]
@jarodw0723 OK, Thanks.
