### ISSUE TITLE
Greyed out vp/libs/*  directories

### ISSUE THREAD

**Issue by ramakis** [nvdla/vp#40]
Hi,

I am new to using Github and need your help.

Under vp/libs/ directory, 3 of the subdirectories (greenlib/, qbox/ & tlm2c) seem to be greyed out and cannot navigate further into them. However I'm able to get into log/ directory. Even the downloaded image has empty directories for these 3. Due to this, cmake build fails with errors saying these directories doesn't contain CMakeLists.txt file.

Am I missing something here? Can you please let me know, how do I resolve this? Thanks much.

Regards
Kishore

**Comment by prasshantg** [comment]
You need to run "git submodule update --init --recursive" from vp directory after cloning

**Comment by ramakis** [comment]
Thanks Prashant. That helped.
