### ISSUE TITLE
NvDlaSubmit: Error IOCTL failed (Invalid argument)

### ISSUE THREAD

**Issue by mireshghallah** [nvdla/vp#41]
Hi,

I have been having this issue for two days! when I run ./nvdla_runtime with flatbuffs, i get it. If I run it with nvdla loadble, it runs fine. can anyone please please help me?

**Comment by prasshantg** [comment]
@mireshghallah Please share more detailed steps used and log.

**Comment by mireshghallah** [comment]
> @mireshghallah Please share more detailed steps used and log.
I log into the docker image, I got it from docker hub. I run the docker for VP. then:
#aarch64_toplevel -c aarch64_nvdla.lua (user root, pass nvdla)
#mount -t 9p -o trans=virtio r /mnt
#Cd /mnt
#insmod drm.ko
#insmod opendla_1.ko

then I run: 
./nvdla_runtime --loadable sw/regression/flatbufs/kmd/NN/NN_L0_0_fbuf    --ima
ge sw/regression/images/digits/one.pgm   --rawdump

I get

[  274.164499] Task execution failed
NvDlaSubmit: Error IOCTL failed (No such process)
(DLA_RUNTIME) Error 0x0003000f: (propagating from Runtime.cpp, function submitInternal(), line 666)
(DLA_TEST) Error 0x00000004: runtime->submit() failed (in RuntimeTest.cpp, function runTest(), line 387)
(DLA_TEST) Error 0x00000004: (propagating from RuntimeTest.cpp, function run(), line 440)

and it stalls. Thanks for you response!

**Comment by mireshghallah** [comment]
> @mireshghallah Please share more detailed steps used and log.

This is the full log @prasshantg , thanks!
./nvdla_runtime --loadable sw/regression/flatbufs/kmd/NN/NN_L0_0_fbuf    --ima
ge sw/regression/images/digits/one.pgm   --rawdump
creating new runtime context...
Emulator starting
pgm2dimg 1 28 28 1 896 25088 25088
submitting tasks...
Work Found!
Work Done
[  273.243657] Enter:dla_read_network_config
[  273.244739] Exit:dla_read_network_config status=0
[  273.245168] Enter: dla_initiate_processors
[  273.247400] Enter: dla_submit_operation
[  273.247814] Prepare Convolution operation index 0 ROI 0 dep_count 1
[  273.248331] Enter: dla_prepare_operation
[  273.248987] processor:Convolution group:0, rdma_group:0 available
[  273.249510] Enter: dla_read_config
[  273.251989] Exit: dla_read_config
[  273.252387] Exit: dla_prepare_operation status=0
[  273.252815] Enter: dla_program_operation
[  273.253180] Program Convolution operation index 0 ROI 0 Group[0]
[  273.259486] no desc get due to index==-1
[  273.259993] no desc get due to index==-1
[  273.260316] no desc get due to index==-1
[  273.260628] no desc get due to index==-1
[  273.260951] no desc get due to index==-1
[  273.261328] Enter: dla_op_programmed
[  273.263172] Update dependency operation index 3 ROI 0 DEP_COUNT=3
[  273.263723] Update dependency operation index 1 ROI 0 DEP_COUNT=1
[  273.264248] enable SDP in dla_update_dependency as depdency are resolved
[  273.264780] Enter: dla_enable_operation
[  273.265172] exit dla_enable_operation without actual enable due to processor hasn't been programmed
[  273.267458] Exit: dla_enable_operation status=0
[  273.268005] Exit: dla_op_programmed
[  273.268359] Exit: dla_program_operation status=0
[  273.268863] Exit: dla_submit_operation
[  273.269403] Enter: dla_dequeue_operation
[  273.271514] Dequeue op from Convolution processor, index=3 ROI=0
[  273.272193] Enter: dla_submit_operation
[  273.272540] Prepare Convolution operation index 3 ROI 0 dep_count 2
[  273.273095] Enter: dla_prepare_operation
[  273.273570] processor:Convolution group:1, rdma_group:0 available
[  273.276008] Enter: dla_read_config
[  273.276642] Exit: dla_read_config
[  273.277050] Exit: dla_prepare_operation status=0
[  273.277557] Enter: dla_program_operation
[  273.279742] Program Convolution operation index 3 ROI 0 Group[1]
[  273.284573] no desc get due to index==-1
[  273.285095] no desc get due to index==-1
[  273.285490] no desc get due to index==-1
[  273.287489] no desc get due to index==-1
[  273.287998] no desc get due to index==-1
[  273.288415] Enter: dla_op_programmed
[  273.288830] Update dependency operation index 6 ROI 0 DEP_COUNT=3
[  273.289358] Update dependency operation index 4 ROI 0 DEP_COUNT=2
[  273.291504] Exit: dla_op_programmed
  273.291927] Exit: dla_program_operation status=0
[  273.292412] Exit: dla_submit_operation
[  273.292855] Exit: dla_dequeue_operation
[  273.293299] Enter: dla_submit_operation
[  273.293677] Prepare SDP operation index 1 ROI 0 dep_count 0
[  273.296893] Enter: dla_prepare_operation
[  273.297540] processor:SDP group:0, rdma_group:0 available
[  273.299220] Enter: dla_read_config
[  273.299826] Exit: dla_read_config
[  273.300197] Exit: dla_prepare_operation status=0
[  273.300599] Enter: dla_program_operation
[  273.300937] Program SDP operation index 1 ROI 0 Group[0]
[  273.305378] no desc get due to index==-1
[  273.306120] no desc get due to index==-1
[  273.306524] no desc get due to index==-1
[  273.306846] no desc get due to index==-1
[  273.307207] Enter: dla_op_programmed
[  273.307525] Update dependency operation index 4 ROI 0 DEP_COUNT=1
[  273.307989] enable SDP in dla_update_dependency as depdency are resolved
[  273.308517] Enter: dla_enable_operation
[  273.308883] exit dla_enable_operation without actual enable due to processor hasn't been programmed
[  273.309511] Exit: dla_enable_operation status=0
[  273.312231] Exit: dla_op_programmed
[  273.312573] Exit: dla_program_operation status=0
[  273.312944] Enter: dla_enable_operation
[  273.313411] Enable SDP operation index 1 ROI 0
[  273.315450] Enter: dla_op_enabled
[  273.315828] Update dependency operation index 0 ROI 0 DEP_COUNT=1
[  273.316341] enable Convolution in dla_update_dependency as depdency are resolved
[  273.316974] Enter: dla_enable_operation
[  273.317368] Enable Convolution operation index 0 ROI 0
[  273.323834] Enter: dla_op_enabled
[  273.324281] Exit: dla_op_enabled
[  273.324617] Exit: dla_enable_operation status=0
[  273.325023] Exit: dla_op_enabled
[  273.325331] Exit: dla_enable_operation status=0
[  273.327196] Exit: dla_submit_operation
[  273.327567] Enter: dla_dequeue_operation
[  273.328011] Dequeue op from SDP processor, index=4 ROI=0
[  273.328475] Enter: dla_submit_operation
[  273.328840] Prepare SDP operation index 4 ROI 0 dep_count 0
[  273.329372] Enter: dla_prepare_operation

Info: NV_NVDLA_cdma.cpp: 1265:NV_NVDLA_cdma::DirectConvDataResponseSequencerCommon, invalid configuration cdma_entries_, set value is 0x6, it shall be 0x7FF.
[  274.093235] processor:SDP group:1, rdma_group:1 available
[  274.093640] Enter: dla_read_config
[  274.095329] Exit: dla_read_config
[  274.095654] Exit: dla_prepare_operation status=0
[  274.096066] Enter: dla_program_operation
[  274.096367] Program SDP operation index 4 ROI 0 Group[1]
[  274.137230] no desc get due to index==-1
[  274.137887] no desc get due to index==-1
[  274.138293] no desc get due to index==-1
[  274.138632] no desc get due to index==-1
[  274.138946] Enter: dla_op_programmed
[  274.139285] Update dependency operation index 7 ROI 0 DEP_COUNT=2
[  274.139765] Exit: dla_op_programmed
[  274.140081] Exit: dla_program_operation status=0
[  274.140498] Enter: dla_enable_operation
[  274.140888] Enable SDP operation index 4 ROI 0
[  274.146552] Enter: dla_op_enabled
[  274.146918] Update dependency operation index 3 ROI 0 DEP_COUNT=2
[  274.147420] Exit: dla_op_enabled
[  274.147728] Exit: dla_enable_operation status=0
[  274.148024] Exit: dla_submit_operation
[  274.148275] Exit: dla_dequeue_operation
[  274.148530] Enter: dla_submit_operation
[  274.148829] Prepare PDP operation index 2 ROI 0 dep_count 1
[  274.149306] Enter: dla_prepare_operation
[  274.153612] processor:PDP group:0, rdma_group:0 available
[  274.154330] Enter: dla_read_config
[  274.154818] Exit: dla_read_config
[  274.155137] Exit: dla_prepare_operation status=0
[  274.155455] Enter: dla_program_operation
[  274.155852] Program PDP operation index 2 ROI 0 Group[0]
[  274.156411] group id 0 rdma id 0
[  274.162354] Invalid dst_data.mem_type: 9216
[  274.162859] Exit: dla_program_operation status=-3
[  274.163267] Exit: dla_submit_operation
[  274.163612] Failed to submit PDP op from index 2
[  274.164029] Exit: dla_initiate_processors status=-3
[  274.164499] Task execution failed
NvDlaSubmit: Error IOCTL failed (No such process)
(DLA_RUNTIME) Error 0x0003000f: (propagating from Runtime.cpp, function submitInternal(), line 666)
(DLA_TEST) Error 0x00000004: runtime->submit() failed (in RuntimeTest.cpp, function runTest(), line 387)
(DLA_TEST) Error 0x00000004: (propagating from RuntimeTest.cpp, function run(), line 440)

**Comment by mireshghallah** [comment]
@prasshantg i figured it out!! the las release of the docker and all the sw/vp repos, (the one for 24days ago, which added support for int8) has messed things up with the flatbufers. They do not work anymore. I reverted back to previous releases and it works!!!

**Comment by fisherxue** [comment]
@mireshghallah What commit did you revert to that worked? Thanks!

**Comment by mireshghallah** [comment]
> @mireshghallah What commit did you revert to that worked? Thanks!

Hey! so I do not know what version of the repo it exactly was, but the docker vp was 1.3. I can remember that the repository was the last stable release before May 27th I guess, or the int8 update. Any version that creates only opendla.ko and not opendla_1 and opendla_2 would work!

**Comment by arvindhbti** [comment]
@prasshantg i am facing the same issue when running with NN_L0_0_fbuf. But when i am running my alexnet i got fast-math.nvdla and when i am running my input cat.pgm it is giving error like


# ./nvdla_runtime --loadable fast-math.nvdla --image cat.pgm 
creating new runtime context...
Emulator starting
pgm2dimg 1 360 480 1 7264 1648928 16489280
(DLA_TEST) Error 0x00000004: Mismatched width: 480 != 227 (in TestUtils.cpp, function createImageCopy(), line 156)
(DLA_TEST) Error 0x00000004: (propagating from RuntimeTest.cpp, function copyImageToInputTensor(), line 100)
(DLA_TEST) Error 0x00000004: (propagating from RuntimeTest.cpp, function setupInputBuffer(), line 162)
(DLA_TEST) Error 0x00000004: (propagating from RuntimeTest.cpp, function runTest(), line 382)
(DLA_TEST) Error 0x00000004: (propagating from RuntimeTest.cpp, function run(), line 440)
Shutdown signal received, exiting
(DLA_TEST) Error 0x00000004: (propagating from main.cpp, function launchTest(), line 87)



Please @prasshantg help me out.Thanks

**Comment by prasshantg** [comment]
@arvindhbti you build alexnet for 227x227 input but using image of 480x360 you need to use same input image as input dimensions set in network

**Comment by sunny-yellow** [comment]
> @prasshantg i figured it out!! the las release of the docker and all the sw/vp repos, (the one for 24days ago, which added support for int8) has messed things up with the flatbufers. They do not work anymore. I reverted back to previous releases and it works!!!

Hello, I would like to ask you a question. when I run the flatbufs on my board not in vp, I also met the problem as you said. Do you kown why?
