### ISSUE TITLE
Dnn network runtime time is desired? is there any plan or guide about this

### ISSUE THREAD

**Issue by blueardour** [nvdla/vp#5]
from the [sw#9](https://github.com/nvdla/sw/issues/9#issuecomment-354951996)
it seems that currently, we can't get the execution time of a network.
However, this is a very important profiling data to estimate the performance of the DLA core.

May I know how to dump the execution time or cycle number of a CNN network by c model (or system c)?
Is there any plan from nvidia or guide  if I want to dig the problem myself?

ps. Another issue troubles me is the compiler seems not support layers of prelu, deconv and so on. I might be better to open another page to talk about it.

**Comment by jarodw0723** [comment]
The current C model is a behavior model and does not support performance profiling. We do have plan for a performance model, but there's no timeline for that yet. 

Currently you can check out our performance calculator in https://github.com/nvdla/hw/blob/nvdlav1/perf/NVDLA_OpenSource_Performance.xlsx

Also we have plan to release a hybrid platform with NVDLA inside the FPGA in 2018-H1, I think you will be able to measure the performance directly.

**Comment by prasshantg** [comment]
I am closing this issue. Please reopen if still have some questions regarding performance measurement.
