### ISSUE TITLE
vp build error when final link 

### ISSUE THREAD

**Issue by HongshiTan** [nvdla/vp#7]
hi all:
i got an error when i try to build vp by the method in readme, behind is the error information,
"/lib/libnvdla_cmod.so: undefined reference to `sc_core::sc_vector_base::make_name(char const*, unsigned long)'
collect2: error: ld returned 1 exit status"

systemc is 2.3.0,
hw  is on branch nvdlav1
it is looks like some wrong with hw ?

**Comment by jarodw0723** [comment]
It looks like SystemC library is not properly linked, can you share the content in vp/CMakeFiles/aarch64_toplevel.dir/link.txt?

**Comment by HongshiTan** [comment]
hi jarodw0723:
[link.txt](https://github.com/nvdla/vp/files/1670840/link.txt)

**Comment by HongshiTan** [comment]
hi jarodw0723

I fix this problom. just my mistake
Because  I have installed gcc-4.9.3 as hw project specificed in its Makefile, and compile hw by gcc 4.9.3
but when it comes to vp, my local gcc is  5.4.0,  I unify this, and there is no link error

very thanks for your replay!
